### ISSUE TITLE
Can this be used of an example of a "Clean Architecture"?

### ISSUE THREAD

**Issue by littlepea** [brandon-rhodes/publicanus#1]
Hi @brandon-rhodes !

I've watched your talk about [The Clean Architecture in Python](https://www.youtube.com/watch?v=DJtef410XaM) and it's a great idea but I can't imagine how to apply this to a Django project...

The problem is that Django heavily relies on Models through all layers of the application. 
If I can't use models in my "functional core" and consider the Django ORM as I/O I can achieve this kind of architecture of course by making "adapters" that transform the ORM queries into suitable data structures to pass into the "core". But this way I'll be adding overhead and can't use a lot of the Django benefits like Generic Views, Model Forms, etc...

Does it mean that Django is not really made for this kind of architecture? 

I've been trying to find any examples of Django projects built using this or any other similar architecture (hexagonal, ports&adapters...) and can't find any mentions of it...

So my only hope was to look for your own projects or ask you directly...
Do you think this repository (publicanus) can be considered a good example of such architecture?

Thanks! :)

**Comment by brandon-rhodes** [comment]
I think you are correct that Django is not designed to support code that keeps I/O at the top level and leaves subroutines innocent of needing to know where data comes from or where it goes. This old Django Dash project seems to attempt an interesting maneuver: it uses multiple inheritance to combine, at the last minute, the I/O-laden Django model class with a class that is concerned only with the data. But I am not sure whether I can recommend this as a good approach for Django apps in general, because I think I only used the technique in this one tiny project, which never saw any further development since it was a prototype written only for the competition.

Unless you can find an example of someone else using my multiple-inheritance technique to write real Django apps, then I think we have to conclude that the approach was entirely unique to this one project. It might be a good idea, or it might be a bad one, but this one quick experiment was probably far too limited to demonstrate whether it would really be a good way of using Django effectively in a large project.

So: because, as far as I know, this technique never caught on in the Django community, I don’t think that this can be held up as a wonderful example of Clean Architecture — simply because the project did not last long enough or grow big enough or even really get deployed seriously, so we don't know whether the patterns it sets up would work well for a real-life team of developers trying to use Django. Feel free to try out any of the ideas here in your own projects, though!

**Comment by littlepea** [comment]
Yes, this is the conclusion I've come to that you can add some additional layers to a Django application to make it cleaner and make sure that the business logic is not in the views or models. 
But what seems almost impossible to do is to make the business core not depend on anything from Django, it's possible but it would be "fighting" against the framework and probably counterproductive...

Also, it seems that you have to structure everything around Django applications making it look almost like SOA, which is great for service-level isolation if in future you want to actually use SOA and can break the services down by the lines of Django applications, but again it means you have to fully give into the framework...

So let's assume you can still happily do things the Django-way and keep it relatively clean and structured... But what to do with testing? It seems like it would be really hard to do unit testing without heavy mocking in Django, even if you try to isolate the business logic into a specific layer because that layer has dependencies on a lot of Django stuff.
It seems like the only answer is mocking all that external stuff out...

Sorry for using the GitHub issues as a place for an abstract conversation, I just wanted to pick your brain specifically rather than Reddit or some Google group... Big fan of your talks! :)

**Comment by brandon-rhodes** [comment]
No problem — good luck as you try to figure out a good Django testing story — and I'm glad you have found my talks helpful!

**Comment by littlepea** [comment]
I think Django testing story is similar to the Rails testing story, it's all about mocking...

We're doing something like this in our project, we have a service layer that gets data from I/O bound external services like ORM and then our business logic can use the data gathered from those services (as django Models and query sets already executed), we can integration-test those services and mock them in our unit tests, same can be done to various adapters (following the rule "Don't mock what you don't own").

This way we can have our unit tests very fast, but need to get very good at mocking... I just wish we didn't have to... :)
